<form method="post" action="<?= $block->getFormAction() ?>">
<!-- <fieldset style="margin: 0 auto; width: 50%"> -->
    <div>
        <label for="first_name"><?= __("First Name") ?></label>
        <input type="text" name="first_name" data-validate="{required:true}"/>
    </div>
    <div>
        <label for="last_name"><?= __("Last Name") ?></label>
        <input type="text" name="last_name" data-validate="{required:true}"/>
    </div>
    <div>
        <label for="email"><?= __("email") ?></label>
        <input type="email" name="email" data-validate="{required:true, 'validate-email':true}"/>
    </div>
    <div>
        <label for="feedback"><?= __("Feedback") ?></label>
        <textarea name="feedback" class="input-text" data-validate="{required:true}"></textarea>
        <!-- <input type="text" name="feedback" data-validate="{required:true}"/> -->
    </div>
    <input type="submit" value="<?= __("Submit") ?>" />
<!-- </fieldset> -->
</form>