<?php if ($block->isHomepage()): ?>
<div class="feedback-scroller">
   <h3>Accepted Feedbacks</h3>
   <ul class="scroller-list">
       <?php $approvedFeedback = $block->getApprovedFeedback(); ?>
       <?php if ($approvedFeedback->getSize() > 0): ?>
           <?php foreach ($approvedFeedback as $feedback): ?>
               <li class="scroller-item">
                   <strong>Name:</strong> <?= $feedback->getData("firstName") ?> <?= $feedback->getData('lastName') ?><br>
                   <strong>Feedback:</strong> <?= $feedback->getFeedback() ?><br>
                   <strong>Email:</strong> <?= $feedback->getEmail() ?><br>
               </li>
            
           <?php endforeach; ?>
       <?php else: ?>
        <li class="no-feedback">No approved feedback available.</li>
       <?php endif; ?>
   </ul>
  
</div>
<?php endif; ?>

<style>
    .feedback_scroller{
      border:2px solid #000;
      font-family:arial;
      height:100px;
      width:100px;
    }
    .scroller-list{
      list-style:none;
      max-height:100px;
      margin:0;
      overflow:auto;
      padding:0;
      /* text-indent:10px; */
    }
    .scroller-item{
      line-height:25px;
    }
    .scroller-item:nth-child(even){
      background:#eee;
    }

</style>