<?php $collection  = $block->getFeedbackData();?>
<?php if ($collection) : ?>

    <div class="container">
        <div class="name">
            <h2>
                <?= $collection->getData('firstName') . ' ' . $collection->getData('lastName') ?>

            </h2>
        </div>
        <div class="comment">
            <h3>
                <?= $collection->getFeedback() ?>
            </h3>
        </div>
        <div class="butttons">
            <a href=<?= $block->setAccept($collection->getId()); ?>>Accept</a>
            <a href=<?= $block->setReject($collection->getId()); ?>>Reject</a>
        </div>
    </div>
<?php else : ?>
    <p>Data not found or not loaded correctly.</p>
<?php endif; ?>